### PR TITLE
Authenticate and set project during initialize

### LINKED ISSUE #150: Link Earth Engine to Cloud Projects
Google established that all Earth Engine usage must be linked to Cloud projects; this is the schedule by Google:

- As of June 2024, all new Earth Engine access requires a Cloud project.
- Starting September 16, 2024, we will be limiting quotas* for accounts without Cloud projects, and most new Earth Engine features will only be available to users of Cloud projects.
- Starting November 13, 2024, all Earth Engine access will require a Cloud project.

We need to make the changes in the plugin (before Nov 13):

1. Creating a transition guide (new and existing users), the process of creating and linking a Cloud Project for newbies would be difficult (example guide: https://courses.spatialthoughts.com/gee-sign-up.html)
2. Register the cloud project ID (e.g. with `ee.Initalize(project=project-id)`), also see https://github.com/gee-community/qgis-earthengine-plugin/issues/143#issuecomment-2030227202
3. Save and restore the cloud project ID (when e.g. restore a Qgis project)

Some of these issues we have discussed here partially: #142

Google document about this change in detail: https://docs.google.com/document/d/1M2WO_--nF7OErnChsLe4Tyt2NOXaYyFdDSLs-ZP8byE/edit?resourcekey=0-otesbid4q7dn3BLCl-3O5Q

### PR DESCRIPTION
**Pull request by gena**
* Fixed bugs during first time start, making sure user is asked for authentication and project selection if needed
* Implemented a simple UI for Authentication and Set Project (added icons, added menu items, added actions)

Fixes #150

### CODE REVIEW

**Comment by XavierCLL** [comment]
Issue 1:

In the process to sign-in, If the user leaves the Project ID empty (for example the user want to create the project after sign-in and then setup it later using the "Set project" option), if you reload the plugin or restart Qgis, the plugin crash because the parameter "project" in credentials file is empty. 

We can fix it checking if the project ID introduced by the user is empty or not, if so, not write the parameter "project" in credentials file to avoid the crash. Without that parameter, if the user not setup the project and after the deadline, `import ee` going to show an error about the google cloud project, but that is a better way than crashing.

```bash
Traceback (most recent call last):
  File "/home/xavier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs/ee/data.py", line 1481, in getAlgorithms
    .list(parent=_get_projects_path(), prettyPrint=False)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xavier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs/googleapiclient/discovery.py", line 1124, in method
    raise TypeError(
TypeError: Parameter "parent" value "projects/" does not match the pattern "^projects/[^/]+$"
```

**Comment by XavierCLL** [comment]
Issue 2:

In the sign-in process, if for any reason the user close the web-browser without finish the login and/or not accept the permissions, Qgis frozen waiting for the response, and you need to kill Qgis instance.

It is a weird user case that we can fix later.

**Comment by XavierCLL** [comment]
Future feature:

In general I like the implementation, simple and practical, thanks Gena. Remember that we need to release it before Nov 13th.

Thinking as a second version of this implementation, and because for many users setup a project inside the Goggle Cloud platform could be challenging, the ideal is doing something quite similar of how GEE web client does: after sign-in, through API, get the user's projects and let the user select one in a drop list, and also an easy way to create a new project inside the plugin.

**Comment by gena** [comment]
> Issue 1:
> 
> In the process to sign-in, If the user leaves the Project ID empty (for example the user want to create the project after sign-in and then setup it later using the "Set project" option), if you reload the plugin or restart Qgis, the plugin crash because the parameter "project" in credentials file is empty.
> 
> We can fix it checking if the project ID introduced by the user is empty or not, if so, not write the parameter "project" in credentials file to avoid the crash. Without that parameter, if the user not setup the project and after the deadline, `import ee` going to show an error about the google cloud project, but that is a better way than crashing.
> 
> ```shell
> Traceback (most recent call last):
>   File "/home/xavier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs/ee/data.py", line 1481, in getAlgorithms
>     .list(parent=_get_projects_path(), prettyPrint=False)
>      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/xavier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs/googleapiclient/discovery.py", line 1124, in method
>     raise TypeError(
> TypeError: Parameter "parent" value "projects/" does not match the pattern "^projects/[^/]+$"
> ```

Good catch, thanks! I will add a check to prevent breaking EE.

**Comment by gena** [comment]
> Future feature:
> 
> In general I like the implementation, simple and practical, thanks Gena. Remember that we need to release it before Nov 13th.
> 
> Thinking as a second version of this implementation, and because for many users setup a project inside the Goggle Cloud platform could be challenging, the ideal is doing something quite similar of how GEE web client does: after sign-in, through API, get the user's projects and let the user select one in a drop list, and also an easy way to create a new project inside the plugin.

There was no time to fully replicate the Code Editor functionality, but it's one of improvements. To do it directly from Python and without installing `gcloud` it will require adding one more scope to list resources (Cloud Projects). Though boundary cases such as "User already authenticated EE before installing plugin" will have to be taken into account, forcing reauthentication to ensure the Oauth2 token has access.

**Comment by gena** [comment]
> Issue 2:
> 
> In the sign-in process, if for any reason the user close the web-browser without finish the login and/or not accept the permissions, Qgis frozen waiting for the response, and you need to kill Qgis instance.
> 
> It is a weird user case that we can fix later.

Yes, I actually tested this, but ignored as this is something happening in Google Cloud libs. Killing QGIS instance for these few runs is an acceptable workaround for now.

**Pull request merged**
