### PR TITLE
Restore readme

### PR DESCRIPTION
**Pull request by XavierCLL**
Hi @gena 

I'm making these changes to update the README file and plugin status:
* Removing the Ukraine section, as it's been included for some time.
* Removing your personal funding in this community project, since this project represents the collective effort of many contributors like myself.

Regars
Xavier

### CODE REVIEW

**Comment by gena** [comment]
I don't this this change makes sense. Ukrainian people are still suffering a lot from unprovoked Russian war, only tonight Russia shot more than 80 cruise, ballistic, and other long-range missiles at Ukraine. Keeping this banner is the least thing I can do on my personal OSS project. It's the right thing to do at this time.

**Comment by XavierCLL** [comment]
OMG! @gena!! I am not talking about the conflict Russia/Ukraine of course that is terrible! I am talking about that banner that has been here for more than two years, and I think that is ok. there are many problems in the world right now, how about Gaza? the famine? climate change? migration? poberty? and a large etc... So, we need a banner for all of them... is the conflict in Ukraine more important than the other ones? I don't want to compare those... but the main goal of this OSS app is not to fix global problems at all, there are many and better other ways....

**Comment by gena** [comment]
The Russian full scale invasion of Ukraine is indeed taking longer than two years. The banner is there to stay to demonstrate this project supports Ukraine as this is done by 23k+ other OSS projects https://github.com/vshymanskyy/StandWithUkraine/tree/main. I can't solve all world problems, but at the moment it's important to keep it here.

**Comment by gena** [comment]
If you want to argue - ask the authors of these projects, some are far more popular like https://github.com/Leaflet/Leaflet developed by @mourner, why they still keep the banner/header text on their OSS project websites active and why this is important.

**Comment by XavierCLL** [comment]
I just wanted to restore the readme file and be more "neutral", not including wars or political issues... but that's okay, we can keep it.

**Pull request closed without merging**
