### PR TITLE
Add support for dependencies using paver, clean-up

### PR DESCRIPTION
**Pull request by gena**
Reorganized dependencies using paver, try this to test it:

* pip install paver
* paver setup
* paver install

### CODE REVIEW

**Comment by XavierCLL** [comment]
Hi Gena, I don't sure about use paver, what is the idea? distribute the plugin with that extlibs dir? (I not sure if that is multiplatform) or the user requires to execute some command? the common user wants plug and play without any intervention to use the plugin

**Comment by gena** [comment]
The end-user won't be required to run anything except installing plugin, extlibs will include platform-specific dependencies, the idea is to avoid pip install (which is apparently error-prone, so we won't get smooth installs). It seems recent QGIS plugins use this approach (google for qgis3 paver).

**Comment by XavierCLL** [comment]
I have never used paver before, when I try to execute paver install it says "---> pavement.install" no more.  When I try to use the plugin it says "cannot import ee" form "import ee" does it require to change all imports using extlibs?

why qgiscommons in requirenmets.txt?

**Comment by gena** [comment]
Try updating, it should be gone (left from copy/paste).

I'm not 100% happy with the paver approach either, but avoiding any slow-down during plugin installation should be a good thing, plus we can control which EE version is used for a specific plugin (more consistent).

**Comment by gena** [comment]
you need to run paver setup first, paver install just creates a softlink

**Comment by gena** [comment]
Let's move chat to https://gitter.im/gee-community/qgis-earthengine-plugin# ;)

**Pull request merged**
